name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Hello from self-hosted runner!"
